In [1]:
import pandas as pd
import numpy as np
from pandas.tseries.holiday import USFederalHolidayCalendar
pd.options.display.max_columns = 0

In [2]:
#FARS dataset
#I had to locally download and edit .csv names so they wouldn't overwrite
url15 = 'https://raw.githubusercontent.com/safe-routes/Build-SafeRoutes-DS/master/accident2015.csv'
url16 = 'https://raw.githubusercontent.com/safe-routes/Build-SafeRoutes-DS/master/accident2016.csv'
url17 = 'https://raw.githubusercontent.com/safe-routes/Build-SafeRoutes-DS/master/accident2017.csv'
ac15 = pd.read_csv(url15)
ac16 = pd.read_csv(url16) 
ac17 = pd.read_csv(url17)

In [3]:
#file with city tags (California)
catxt = 'https://raw.githubusercontent.com/safe-routes/Build-SafeRoutes-DS/master/CA_FedCodes_20190301.txt'
ca = pd.read_table(catxt, delimiter = '|')

C:\Users\EDC\Anaconda3\envs\environ1\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [4]:
ac15.head()

   STATE  ST_CASE  VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  PERNOTMVIT  ...  HOSP_HR  HOSP_MN  CF1  CF2  CF3  FATALS  DRUNK_DR
0      1    10001         1         1         0     0           0  ...       88       88    0    0    0       1         1
1      1    10002         1         1         0     0           0  ...       88       88    0    0    0       1         0
2      1    10003         1         1         0     0           0  ...       99       99    0    0    0       1         1
3      1    10004         1         1         0     0           0  ...       88       88    0    0    0       1         1
4      1    10005         2         2         0     0           0  ...       88       88    0    0    0       1         0

[5 rows x 52 columns]

In [5]:
print(ac15.shape)
print(ac16.shape)
print(ac17.shape)

(32538, 52)
(34748, 52)
(34247, 52)

In [6]:
ac15.STATE.value_counts()

48    3190
6     3123
12    2699
13    1329
37    1275
42    1102
36    1061
39    1029
17     914
45     911
26     896
47     888
4      811
29     803
1      784
18     752
51     712
22     698
21     694
28     604
40     590
55     523
34     521
8      507
53     499
5      491
24     479
41     411
27     375
25     327
20     322
32     297
19     282
35     269
49     258
9      257
54     246
31     218
30     204
16     198
23     144
56     129
10     127
46     116
38     111
33     103
15      85
2       60
50      50
44      41
11      23
Name: STATE, dtype: int64

In [7]:
#ca[ca['FEATURE_NAME'] == 'San Francisco']
#GSA is 3290; now we can reduce the main dataset
#County_Numeric is 75

In [8]:
# ac15 = ac15[ac15['CITY'] == 3290]
# print(ac15.shape)
# ac16 = ac16[ac16['CITY'] == 3290]
# print(ac16.shape)
# ac17 = ac17[ac17['CITY'] == 3290]
# print(ac17.shape)

# FILTERING FOR ALL INCIDENTS IN CALIFORNIA (SAN FRANCISCO DATA TOO SMALL!)
# California under 'STATE' feature is 6
ac15 = ac15[ac15['STATE'] == 6]
print(ac15.shape)
ac16 = ac16[ac16['STATE'] == 6]
print(ac16.shape)
ac17 = ac17[ac17['STATE'] == 6]
print(ac17.shape)

(3123, 52)
(3540, 52)
(3304, 52)

In [9]:
ac = ac15.append(ac16)
ac = ac.append(ac17)
ac.shape

(9967, 52)

In [10]:
ac.isnull().sum()

STATE            0
ST_CASE          0
VE_TOTAL         0
VE_FORMS         0
PVH_INVL         0
PEDS             0
PERNOTMVIT       0
PERMVIT          0
PERSONS          0
COUNTY           0
CITY             0
DAY              0
MONTH            0
YEAR             0
DAY_WEEK         0
HOUR             0
MINUTE           0
NHS              0
RUR_URB          0
FUNC_SYS         0
RD_OWNER         0
ROUTE            0
TWAY_ID          0
TWAY_ID2      7209
MILEPT           0
LATITUDE         0
LONGITUD         0
SP_JUR           0
HARM_EV          0
MAN_COLL         0
RELJCT1          0
RELJCT2          0
TYP_INT          0
WRK_ZONE         0
REL_ROAD         0
LGT_COND         0
WEATHER1         0
WEATHER2         0
WEATHER          0
SCH_BUS          0
RAIL             0
NOT_HOUR         0
NOT_MIN          0
ARR_HOUR         0
ARR_MIN          0
HOSP_HR          0
HOSP_MN          0
CF1              0
CF2              0
CF3              0
FATALS           0
DRUNK_DR         0
dtype: int64

In [11]:
ac = ac.replace({np.nan:'No_crossroad'}) #the only nans were in TWAY_ID2

In [12]:
#LATITUDE and LONGITUD outliers: 99.9990 x 999.99900
ac[['LATITUDE', 'LONGITUD']].sort_values('LATITUDE', ascending=False).head()

      LATITUDE  LONGITUD
5105   99.9999  999.9999
5647   88.8888  888.8888
3173   77.7777  777.7777
4729   77.7777  777.7777
4609   77.7777  777.7777

In [13]:
ac = ac[ac['LATITUDE'] != 99.999900]

In [14]:
ac[['LATITUDE', 'LONGITUD']].sort_values('LATITUDE', ascending=False).head()

       LATITUDE    LONGITUD
5647  88.888800  888.888800
4609  77.777700  777.777700
3173  77.777700  777.777700
4729  77.777700  777.777700
3574  41.992389 -123.719178

In [15]:
ac[ac['LATITUDE'] == 0.000000].head()

Empty DataFrame
Columns: [STATE, ST_CASE, VE_TOTAL, VE_FORMS, PVH_INVL, PEDS, PERNOTMVIT, PERMVIT, PERSONS, COUNTY, CITY, DAY, MONTH, YEAR, DAY_WEEK, HOUR, MINUTE, NHS, RUR_URB, FUNC_SYS, RD_OWNER, ROUTE, TWAY_ID, TWAY_ID2, MILEPT, LATITUDE, LONGITUD, SP_JUR, HARM_EV, MAN_COLL, RELJCT1, RELJCT2, TYP_INT, WRK_ZONE, REL_ROAD, LGT_COND, WEATHER1, WEATHER2, WEATHER, SCH_BUS, RAIL, NOT_HOUR, NOT_MIN, ARR_HOUR, ARR_MIN, HOSP_HR, HOSP_MN, CF1, CF2, CF3, FATALS, DRUNK_DR]
Index: []

In [16]:
ac.shape

(9966, 52)

In [17]:
ac.head()
#Keeping these cols:
#VE_TOTAL = the number of cars involved
#VE_FORMS = the number of cars moving
#PVH_INVL = the number of parked cars
#PEDS = number of pedestrians involved
#MONTH, DAY, YEAR = keep for making a holiday feature (datetime)
#DAY_WEEK = day of the week starting at Sunday (has str NaNs '--')
#HOUR
#NHS - HIGHWAY
#FUNC_SYS = type of trafficway
#ROUTE = type of road
#TWAY_ID, TWAY_ID2 the street names
#LATITUDE, LONGITUD
#HARM_EV = cause of accident
#MAN_COLL = type of collision
#RELJCT_2 = type of junction
#TYP_INT = type of intersection
#WRK_ZONE should be changed to binary 
          #was there roadwork happening 0 no !=0 yes
#REL_ROAD if car was out of bounds 
#LGT_COND should be made into night or day binary
          #1, 4 are day
#WEATHER make into rain binary (2 = rain)

      STATE  ST_CASE  VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  PERNOTMVIT  ...  HOSP_HR  HOSP_MN  CF1  CF2  CF3  FATALS  DRUNK_DR
2146      6    60001         1         1         0     0           0  ...       88       88    0    0    0       1         1
2147      6    60002         2         2         0     0           0  ...       88       88    0    0    0       2         2
2148      6    60003         1         1         0     1           1  ...       88       88    0    0    0       1         0
2149      6    60004         3         3         0     0           0  ...       88       88    3    0    0       1         1
2150      6    60005         1         1         0     1           1  ...       88       88    0    0    0       1         0

[5 rows x 52 columns]

In [18]:
ac = ac.drop(columns = ['STATE', 'ST_CASE', 'PERNOTMVIT',
                        'PERMVIT','PERSONS', 'CITY',
                        'MINUTE', 'RUR_URB', 'RD_OWNER', 'MILEPT',
                        'SP_JUR', 'RELJCT1', 'WEATHER1','SCH_BUS',
                        'WEATHER2', 'RAIL', 'NOT_HOUR', 'NOT_MIN',
                        'ARR_HOUR', 'ARR_MIN', 'HOSP_HR', 'HOSP_MN',
                        'CF1', 'CF2', 'CF3', 'FATALS'])

In [19]:
ac['FUNC_SYS'].value_counts() #no unknowns
#labels:
#1 = interstate
#2 = freeway artery
#3 = general artery
#4 = minor artery
#5 = collector
#7 = local

3     2853
4     2036
2     1687
1     1323
5     1240
7      634
6      186
98       5
96       2
Name: FUNC_SYS, dtype: int64

In [20]:
ac['ROUTE'].value_counts().sort_index()
#1 = interstate
#2 = national highway
#3 = state highway
#6 = local (municipality type)
#9 = UNKNOWN

1    1297
2     408
3    2325
4    1614
5     293
6    3766
7       6
8       3
9     254
Name: ROUTE, dtype: int64

In [36]:
ac[ac['ROUTE'] == 9] #Id just make them local

      VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  COUNTY  DAY  ...  WRK_ZONE  REL_ROAD  LGT_COND  WEATHER  DRUNK_DR  holiday
2738         1         1         0     1      67    2  ...         0         1         4        1         0      0.0
2863         1         1         0     0       5    3  ...         0         4         1        1         1      0.0
2899         1         1         0     0      13   13  ...         0         5         1        1         0      0.0
3076         1         1         0     0      27   23  ...         0         4         1        1         0      0.0
3166         1         1         0     0      83   26  ...         0         4         2        1         1      0.0
3185         2         2         0     0      37    9  ...         0         1         1        1         0      0.0
3309         1         1         0     1      37    7  ...         0         1         3        1         0      0.0
3367         1         1         0     1      75   17  ...         0         1         1        1         0      0.0
3603         2         2         0     0      29   17  ...         0         1         1        1         0      0.0
3616         1         1         0     0      65    5  ...         0         4         1        1         0      0.0
3630         1         1         0     1      39   27  ...         0         1         1        1         0      0.0
3691         1         1         0     0      53    8  ...         0         4         2        8         1      0.0
3833         2         2         0     1      53   10  ...         0         1         2       10         1      0.0
4027         1         1         0     0       7    8  ...         0         4         2        1         1      0.0
4598         1         1         0     2      39   25  ...         0         4         1        1         0      0.0
4621         2         2         0     0      65   15  ...         0         1         2        1         1      0.0
4673         1         1         0     1      65   27  ...         0         1         2        1         1      0.0
4697         2         2         0     0      59    3  ...         0         1         1       10         0      0.0
4765         3         3         0     0      69   23  ...         0         1         4        1         0      0.0
4842         1         1         0     1      65   18  ...         0         1         4        1         0      0.0
4872         1         1         0     1      67   12  ...         0         1         3        1         0      0.0
4896         1         1         0     0       1    9  ...         0         4         3        1         1      0.0
4919         1         1         0     1      93   18  ...         0         1         2        1         0      0.0
4944         2         1         1     0      37    9  ...         0         7         4        1         1      0.0
4945         1         1         0     0      79   24  ...         0         4         1        1         1      0.0
4983         1         1         0     0     109    2  ...         0         4         1        1         0      0.0
4984         2         2         0     0      67   13  ...         0         1         2        1         0      0.0
5010         3         3         0     0      59   18  ...         0         1         1        1         0      0.0
5056         1         1         0     1      67    3  ...         0         4         3       10         1      0.0
5057         2         2         0     0      71   30  ...         0         1         1        1         0      0.0
...        ...       ...       ...   ...     ...  ...  ...       ...       ...       ...      ...       ...      ...
5567         1         1         0     1      37    5  ...         0         1         1        1         0      0.0
5569         1         1         0     1      13    5  ...         0         1         1        1         0      0.0
5572         1         1         0     1      37    7  ...         0         1         3        1         0      0.0
5576         2         2         0     0      37   24  ...         0         1         2        1         0      0.0
5577         1         1         0     0      13   21  ...         0         4         1        1         0      0.0
5578         3         2         1     0      37   20  ...         0         1         1        1         1      0.0
5580         1         1         0     1      65   25  ...         0         1         2        1         0      0.0
5581         3         3         0     0       1   19  ...         0         1         3        1         2      0.0
5582         2         1         1     0      99   17  ...         0         5         3        1         1      0.0
5584         2         2         0     0      71    8  ...         0         1         1        1         1      0.0
5587         1         1         0     0      65   18  ...         0         4         1        1         0      0.0
5588         1         1         0     1      37   22  ...         0         1         3        1         0      0.0
5590         1         1         0     1      19    2  ...         0         1         3        1         0      0.0
5593         1         1         0     1      37   11  ...         0         1         5        1         0      0.0
5594         1         1         0     0      71   11  ...         0         1         1       10         0      0.0
5595         1         1         0     0      71   15  ...         0         4         1        1         0      0.0
5597         1         1         0     0      71   24  ...         0         4         1        1         0      0.0
5598         2         2         0     1      71   25  ...         0         1         3        1         0      0.0
5601         1         1         0     0      19   27  ...         0         1         2        8         0      0.0
5606         7         7         0     0      65   20  ...         0         1         1        1         1      0.0
5607         1         1         0     1      71   15  ...         0         1         1        1         0      0.0
5608         1         1         0     1      77   31  ...         0         5         1        1         0      0.0
5610         1         1         0     1      71    8  ...         0         4         1        1         0      0.0
5611         2         2         0     0      95    5  ...         0         1         1        1         0      0.0
5612         1         1         0     1      85   16  ...         0         1         1        1         0      0.0
5613         2         2         0     0      47   19  ...         0         1         3        1         1      0.0
5614         4         3         1     0      59   27  ...         0         1         1        1         0      0.0
5615         1         1         0     1      37   20  ...         0         1         3        1         0      0.0
5616         2         1         1     0      37   19  ...         0         4         3        1         1      0.0
5617         2         2         0     0     111   16  ...         0         1         1        1         0      0.0

[254 rows x 27 columns]

In [37]:
ac['HARM_EV'].value_counts().sort_index()
#8 = pedestrian
#9 = bicycle
#12 = moving vehicle
#14 = parked vehicle
#15 = unmoterized (other than bikes)
#19 = building
#23 = bridge rail
#25 = concrete traffic barrier
#33 = curb
#42 = tree

1      676
2        5
3        6
5       36
6        1
7        7
8     2390
9      408
10      14
11      14
12    3366
14     205
15      98
16       2
17      45
18      54
19       5
20      20
21      13
23      18
24     184
25     110
26       3
30     153
31      64
32      19
33     712
34      41
35     217
38     154
39      53
40       3
41      27
42     441
43     123
44       4
45       2
46      32
49       2
50       3
52      36
53      17
54      16
58      30
59     129
72       1
73       2
93       1
Name: HARM_EV, dtype: int64

In [23]:
ac['MAN_COLL'].value_counts().sort_index()
#0 not applicable
#1 rear end
#2 head on
#6 angled
#7 sideswipe (same direction)

0     6582
1      689
2      790
6     1499
7      242
8      116
9        9
10       1
11      30
98       7
99       1
Name: MAN_COLL, dtype: int64

In [24]:
ac['RELJCT2'].value_counts().sort_index()
#1 not a junction
#2 intersection
#3 intersection...
#5 ramp
#18 through roadway

1     6468
2     1579
3     1075
4       39
5      250
6       15
7        1
8      252
16       1
17       2
18     116
19      95
20      67
98       3
99       3
Name: RELJCT2, dtype: int64

In [25]:
ac['TYP_INT'].value_counts().sort_index()
#1 not an intersection
#2 four way
#3 T

1     7308
2     1741
3      870
4       19
5        1
6        6
7        1
10      12
98       5
99       3
Name: TYP_INT, dtype: int64

In [26]:
ac['REL_ROAD'].value_counts().sort_index()
#1 roadway
#2 shoulder
#3 median
#4 roadside
#5 outside trafficway
#7 parking lane

1     6465
2      247
3      356
4     2636
5       84
6        7
7       64
8       88
10       6
11       6
98       3
99       4
Name: REL_ROAD, dtype: int64

In [27]:
ac['WEATHER'].value_counts().sort_index()
#1 clear
#2 rain
#10 cloudy

1     8312
2      438
3        1
4       13
5       86
6       18
7        1
8       10
10    1068
98      16
99       3
Name: WEATHER, dtype: int64

In [28]:
ac['DRUNK_DR'].value_counts().sort_index()

0    7163
1    2696
2     106
3       1
Name: DRUNK_DR, dtype: int64

In [38]:
print(ac.shape)
ac.head()
#VE_TOTAL = the number of cars involved
#VE_FORMS = the number of cars moving
#PVH_INVL = the number of parked cars
#PEDS = number of pedestrians involved
#MONTH, DAY, YEAR = keep for making a holiday feature (datetime)
#DAY_WEEK = day of the week starting at Sunday (has str NaNs '--')
#HOUR
#NHS - HIGHWAY
#FUNC_SYS = type of trafficway
#ROUTE = type of road
#TWAY_ID, TWAY_ID2 the street names
#LATITUDE, LONGITUD
#HARM_EV = cause of accident
#MAN_COLL = type of collision
#RELJCT_2 = type of junction
#TYP_INT = type of intersection
#WRK_ZONE should be changed to binary 
          #was there roadwork happening 0 no !=0 yes
#REL_ROAD if car was out of bounds 
#LGT_COND should be made into night or day binary
          #1, 4 are day
#WEATHER make into rain binary (2 = rain)
#DRUNK_DR take a guess

(9962, 27)

      VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  COUNTY  DAY  ...  WRK_ZONE  REL_ROAD  LGT_COND  WEATHER  DRUNK_DR  holiday
2146         1         1         0     0      93    1  ...         0         4         3        1         1      0.0
2147         2         2         0     0      37    1  ...         0         1         3        1         2      0.0
2148         1         1         0     1      59    1  ...         0         1         3        1         0      0.0
2149         3         3         0     0      67    1  ...         1         1         1        1         1      0.0
2150         1         1         0     1      71    2  ...         0         1         2        1         0      0.0

[5 rows x 27 columns]

In [51]:
# Dropping observations with invalid LONGITUDE
# Longitudes cannot be less than -180 NOR greater than 180

ac = ac[ac['LONGITUD'] < 180]

In [52]:
ac.columns

Index(['VE_TOTAL', 'VE_FORMS', 'PVH_INVL', 'PEDS', 'COUNTY', 'DAY', 'MONTH',
       'YEAR', 'DAY_WEEK', 'HOUR', 'NHS', 'FUNC_SYS', 'ROUTE', 'TWAY_ID',
       'TWAY_ID2', 'LATITUDE', 'LONGITUD', 'HARM_EV', 'MAN_COLL', 'RELJCT2',
       'TYP_INT', 'WRK_ZONE', 'REL_ROAD', 'LGT_COND', 'WEATHER', 'DRUNK_DR',
       'holiday'],
      dtype='object')

In [41]:
cal = USFederalHolidayCalendar()
holidays = cal.holidays('2015', '2016', '2017')
ac = ac.join(pd.Series(1, index=holidays, name='holiday'))
ac['holiday'].fillna(0, inplace=True)

ValueError: columns overlap but no suffix specified: Index(['holiday'], dtype='object')

In [53]:
ac.head()

      VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  COUNTY  DAY  ...  WRK_ZONE  REL_ROAD  LGT_COND  WEATHER  DRUNK_DR  holiday
2146         1         1         0     0      93    1  ...         0         4         3        1         1      0.0
2147         2         2         0     0      37    1  ...         0         1         3        1         2      0.0
2148         1         1         0     1      59    1  ...         0         1         3        1         0      0.0
2149         3         3         0     0      67    1  ...         1         1         1        1         1      0.0
2150         1         1         0     1      71    2  ...         0         1         2        1         0      0.0

[5 rows x 27 columns]

In [82]:
# California accidents coordinates (2015-2017)
county_list = [1, 41, 75]
ac_coord = ac[(ac['COUNTY']==1) | (ac['COUNTY']==41) | (ac['COUNTY']==75) | (ac['COUNTY']==85)| (ac['COUNTY']==81) ]

In [83]:
ac_coord.head(1000)

      VE_TOTAL  VE_FORMS  PVH_INVL  PEDS  COUNTY  DAY  ...  WRK_ZONE  REL_ROAD  LGT_COND  WEATHER  DRUNK_DR  holiday
2156         2         2         0     0      85    4  ...         0         1         1        1         0      0.0
2165         5         5         0     0       1    5  ...         0         1         5        1         0      0.0
2166         1         1         0     0       1    1  ...         0         4         3        1         1      0.0
2169         3         3         0     0       1    4  ...         0         1         2        1         0      0.0
2175         2         2         0     1      75   10  ...         0         1         5        1         1      0.0
2198         2         2         0     0       1    8  ...         0         1         1       10         0      0.0
2207         1         1         0     1      85    8  ...         0         1         3       10         0      0.0
2221         1         1         0     1       1   13  ...         0         1         3        1         0      0.0
2223         1         1         0     0      85   11  ...         0         4         3        5         0      0.0
2233         1         1         0     1      85   18  ...         0         1         3        1         0      0.0
2248         1         1         0     0      85   22  ...         0         4         3        1         1      0.0
2254         3         2         1     3       1   23  ...         0         1         3        1         0      0.0
2258         2         2         0     1      85   23  ...         0         1         3        1         0      0.0
2260         1         1         0     0      85   17  ...         0         3         1        1         1      0.0
2295         3         2         1     1      85   26  ...         0         1         1        1         0      0.0
2309         1         1         0     0      85    1  ...         0         4         2        1         1      0.0
2322         1         1         0     1      85   25  ...         0         1         2        1         0      0.0
2339         1         1         0     0      85    7  ...         0         4         2        2         0      0.0
2349         2         2         0     0      85    7  ...         0         1         3        1         1      0.0
2356         2         2         0     0      85    4  ...         0         1         3        1         0      0.0
2398         3         3         0     0       1    6  ...         0         1         2        1         1      0.0
2403         2         2         0     0      85    6  ...         0         1         1       10         0      0.0
2403         1         1         0     0      41   19  ...         0         4         2        2         0      0.0
2413         1         1         0     0       1    6  ...         0         4         1       10         0      0.0
2430         1         1         0     0      41    8  ...         0         4         2        2         0      0.0
2434         1         1         0     1      41   12  ...         0         1         1       10         0      0.0
2435         1         1         0     1      75   16  ...         0         1         1        1         0      0.0
2443         1         1         0     1      41    7  ...         0         1         3       10         0      0.0
2452         1         1         0     1      85   16  ...         0         1         1        1         0      0.0
2469         2         2         0     1       1   25  ...         0         1         2       10         0      0.0
...        ...       ...       ...   ...     ...  ...  ...       ...       ...       ...      ...       ...      ...
5637         2         2         0     0      85   25  ...         0         1         3        1         1      0.0
5686         2         2         0     0      85   24  ...         0         1         3        1         1      0.0
5691         4         3         1     0      85   19  ...         0         1         3        1         0      0.0
5694         2         2         0     0       1   29  ...         0         1         1        1         0      0.0
5704         2         2         0     0      85    9  ...         0         1         3       10         1      0.0
5710         1         1         0     0      85   11  ...         0         4         1        1         0      0.0
5719         5         5         0     1       1   14  ...         0         1         2       10         0      0.0
5731         1         1         0     0       1   28  ...         0         4         3        1         1      0.0
5735         1         1         0     0      85    6  ...         0         3         2        1         1      0.0
5754         1         1         0     1       1    1  ...         0         1         1        1         0      0.0
5755         1         1         0     1       1   12  ...         0         1         3       10         0      0.0
5771         1         1         0     1      85   17  ...         0         1         3        1         0      0.0
5784         1         1         0     0      85   18  ...         0         8         2        1         1      0.0
5789         7         2         5     0      75    6  ...         0         7         1        1         0      0.0
5791         1         1         0     1       1   12  ...         0         1         1        1         0      0.0
5797         3         1         2     1      75    1  ...         0         2         1       10         0      0.0
5801         1         1         0     1      75   28  ...         0         1         1        1         0      0.0
5806         1         1         0     1      75   11  ...         0         1         8       10         0      0.0
5841         1         1         0     1       1   26  ...         0         1         1        1         0      0.0
5892         1         1         0     0       1   26  ...         0         4         1       10         1      0.0
5917         2         2         0     0       1    1  ...         0         1         1        1         0      0.0
5921         2         2         0     0      85   12  ...         0         1         1        1         0      0.0
5924         1         1         0     1      75   22  ...         0         1         5        1         0      0.0
5925         1         1         0     1       1   20  ...         0         1         1        1         0      0.0
5940         1         1         0     0      85   29  ...         0         4         1        1         0      0.0
5944         5         4         1     0      75    1  ...         0         1         1       10         0      0.0
5946         1         1         0     1      75   30  ...         0         1         3        1         0      0.0
5951         1         1         0     0       1   26  ...         0         4         1        2         0      0.0
5952         2         2         0     0      75   23  ...         0         1         1        2         0      0.0
5954         1         1         0     0      85   29  ...         0         4         1        1         0      0.0

[713 rows x 27 columns]

In [47]:
ac_coord = ac_coord[['LATITUDE', 'LONGITUD', 'COUNTY']]

In [84]:
ac_coord.shape

(713, 27)

In [85]:
ac_coord.to_csv('cali_ac_coord.csv', index=False)

## Testing Google Maps API

#### Reading API Key

In [ ]:
with open('GMapsAPI.txt') as f:
    myapi_key = f.readline()
    f.close

In [ ]:
!pip install gmaps

In [ ]:
import gmaps

gmaps.configure(api_key=myapi_key)

#### Importing `earthquake` dataset from gmaps API

In [ ]:
# import gmaps.datasets

# earthquake_df = gmaps.datasets.load_dataset_as_df('earthquakes')
# earthquake_df.head()

In [ ]:
# earthquake_df.shape

#### Ploting Accidents in California accoring to `ac` dataframe

In [ ]:
locations = ac[['LATITUDE', 'LONGITUD']]
weights = ac['VE_TOTAL'] # here using Total of Cars Involved as 'weights'

#locations = earthquake_df[['latitude', 'longitude']]
#weights = earthquake_df['magnitude']

fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))

fig

In [ ]:

# adding layer of directions from LA to San Diego
la = (34.05,-118.24)
sd = (32.71,-117.15)
la2sd = gmaps.directions_layer(la, sd)
fig.add_layer(la2sd)

#### Zooming into San Francisco

In [ ]:
sf_coordinates = (37.775, -122.419444)
gmaps.figure(center=sf_coordinates, zoom_level=12)